name: Unity Build

on:
  workflow_dispatch:
  #push:
    #branches: [main]
    
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    env:
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneWindows64

      - name: Save build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: Build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Build
          path: Build

      - name: Prepare Steam content
        run: |
          mkdir -p Build/steam/content
          cp -r build/* Build/steam/content/

      - name: Deploy to Steam
        uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: "CI Build"
          rootPath: Build/steam
          depot1Path: Build/steam/content
          releaseBranch: yolo
